# Generated by Django 2.2b1 on 2019-03-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='atrist',
            new_name='artist',
        ),
    ]
