# Generated by Django 2.2b1 on 2019-03-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190305_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_fovourite',
            field=models.BooleanField(default=False),
        ),
    ]
