# Generated by Django 2.2b1 on 2019-03-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_is_fovourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_fovourite',
            new_name='is_favourite',
        ),
    ]
